"""Master CSE course catalog (DIU B.Sc. CSE curriculum) — seeded on server startup (upsert by code)."""

# Fixed credit for all catalog courses (not stored per row in this file).
CATALOG_DEFAULT_CREDIT: float = 3.0

# (code, name)
CSE_COURSE_LIST: list[tuple[str, str]] = [
    # --- Core CSE courses ---
    ("CSE 112", "Computer Fundamentals"),
    ("CSE 113", "Programming and Problem Solving"),
    ("CSE 114", "Programming and Problem Solving Lab"),
    ("CSE 115", "Introduction to Biology & Chemistry for Computation"),
    ("CSE 121", "Electrical Circuits"),
    ("CSE 122", "Electrical Circuits Lab"),
    ("CSE 123", "Data Structure"),
    ("CSE 124", "Data Structure Lab"),
    ("CSE 212", "Discrete Mathematics"),
    ("CSE 213", "Algorithms"),
    ("CSE 214", "Algorithms Lab"),
    ("CSE 215", "Electronic Devices and Circuits"),
    ("CSE 216", "Electronic Devices and Circuits Lab"),
    ("CSE 221", "Object Oriented Programming"),
    ("CSE 222", "Object Oriented Programming Lab"),
    ("CSE 223", "Digital Logic Design"),
    ("CSE 224", "Digital Logic Design Lab"),
    ("CSE 225", "Data Communication"),
    ("CSE 226", "Numerical Methods"),
    ("CSE 227", "Systems Analysis and Design"),
    ("CSE 228", "Theory of Computation"),
    ("CSE 311", "Database Management System"),
    ("CSE 312", "Database Management System Lab"),
    ("CSE 313", "Compiler Design"),
    ("CSE 314", "Compiler Design Lab"),
    ("CSE 315", "Software Engineering"),
    ("CSE 316", "Artificial Intelligence"),
    ("CSE 317", "Microprocessor and Microcontrollers"),
    ("CSE 321", "Computer Networks"),
    ("CSE 322", "Computer Networks Lab"),
    ("CSE 323", "Operating Systems"),
    ("CSE 324", "Operating Systems Lab"),
    ("CSE 325", "Instrumentation and Control"),
    ("CSE 326", "Social and Professional Issues in Computing"),
    ("CSE 411", "Computer Graphics"),
    ("CSE 412", "Computer Graphics Lab"),
    ("CSE 413", "Computer Architecture and Organization"),
    # --- General education (37.5 credits) ---
    ("ENG 101", "Basic Functional English and English Spoken"),
    ("ENG 102", "Writing and Comprehension"),
    ("MAT 101", "Mathematics I"),
    ("MAT 102", "Mathematics II: Calculus, Complex Variables & Linear Algebra"),
    ("MAT 211", "Engineering Mathematics"),
    ("PHY 101", "Physics I"),
    ("PHY 102", "Physics II"),
    ("PHY 103", "Physics II Lab"),
    ("BNS 101", "Bangladesh Studies (History of Independence & Contemporary Issues)"),
    ("AOL 101", "Art of Living"),
    ("STA 101", "Statistics and Probability"),
    ("ACT 327", "Financial and Managerial Accounting"),
    ("ECO 426", "Engineering Economics"),
    # --- Project courses ---
    ("CSE 498", "FYDP / Capstone Project (Phase I)"),
    ("CSE 499", "FYDP / Capstone Project (Phase II)"),
    # --- Electives (general) ---
    ("CSE 431", "Machine Learning"),
    ("CSE 432", "Natural Language Processing"),
    ("CSE 433", "Artificial Neural Networks"),
    ("CSE 434", "Pattern Recognition"),
    ("CSE 435", "Soft Computing"),
    ("CSE 436", "Digital Image Processing"),
    ("CSE 437", "Computer Vision"),
    ("CSE 438", "Business Intelligence"),
    # --- Specialization: Software Development ---
    ("CSE 441", "UI and UX Design"),
    ("CSE 442", "Software Quality Assurance"),
    ("CSE 443", "Web Computing"),
    ("CSE 444", "Software Architecture and Design Pattern"),
    ("CSE 445", "Intellectual Property and Contract Law"),
    ("CSE 446", "Mobile Applications Development"),
    ("CSE 447", "Concurrent and Distributed Programming"),
    ("CSE 448", "Virtual Reality and 3D Games"),
    # --- Specialization: Network and Communication ---
    ("CSE 451", "Cloud Computing and Services"),
    ("CSE 452", "Optical Fiber Communication"),
    ("CSE 453", "Wireless Sensor Network"),
    ("CSE 454", "Cyber Security and Forensics"),
    ("CSE 455", "High Performance Computing"),
    ("CSE 456", "Network Programming"),
    ("CSE 457", "Wireless and Cellular Communication"),
    # --- Specialization: Algorithms ---
    ("CSE 461", "Algorithm Engineering"),
    ("CSE 462", "Computational Complexity"),
    ("CSE 463", "Advanced Algorithms"),
    ("CSE 464", "Basic Graph Theory"),
    ("CSE 465", "Algorithmic Game Theory"),
    ("CSE 466", "Bioinformatics Algorithm"),
    ("CSE 467", "Algorithm for Distributed Computation"),
    # --- Specialization: Embedded Systems and Robotics ---
    ("CSE 471", "Introduction to Embedded Systems"),
    ("CSE 472", "Internet of Things (IoT)"),
    ("CSE 473", "Robotics"),
    ("CSE 474", "VLSI Design"),
    ("CSE 475", "Micro-sensors"),
    ("CSE 476", "Sensor Manufacturing and Process Control"),
    ("CSE 477", "Introduction to Nanotechnology and Nanodevices"),
    ("CSE 478", "Additive Manufacturing Engineering"),
]
